// lib/incident.js — auto-create Gitea issue when pool exhausted > threshold.
// ponytail: minimal — caller provides a token + base URL. No retries on rate-limit.

export const INCIDENT_DEFAULT_THRESHOLD_MS = 5 * 60 * 1000; // 5 min
export const INCIDENT_DEFAULT_COOLDOWN_MS = 30 * 60 * 1000; // 30 min between incidents per provider
export const INCIDENT_TIMEOUT_MS = 5000;

export class IncidentReporter {
  constructor({ token, baseUrl, repo, thresholdMs = INCIDENT_DEFAULT_THRESHOLD_MS, cooldownMs = INCIDENT_DEFAULT_COOLDOWN_MS, fetchImpl } = {}) {
    if (!token) throw new Error('incident: token required');
    if (!baseUrl) throw new Error('incident: baseUrl required');
    if (!repo || !repo.includes('/')) throw new Error('incident: repo (owner/name) required');
    this._token = token;
    this._baseUrl = baseUrl.replace(/\/+$/, '');
    this._repo = repo;
    this._thresholdMs = thresholdMs;
    this._cooldownMs = cooldownMs;
    this._lastIncidentAt = new Map(); // provider -> epochMs
    this._fetch = fetchImpl || (typeof fetch !== 'undefined' ? fetch : () => { throw new Error('incident: no fetch available'); });
  }

  // Should we report now? Pure; does not perform I/O.
  shouldReport(provider, exhaustedSince, now = Date.now()) {
    if (!provider) return false;
    if (!Number.isFinite(exhaustedSince)) return false;
    if (now - exhaustedSince < this._thresholdMs) return false;
    const last = this._lastIncidentAt.get(provider);
    if (Number.isFinite(last) && now - last < this._cooldownMs) return false;
    return true;
  }

  markReported(provider, at = Date.now()) {
    this._lastIncidentAt.set(provider, at);
  }

  resetCooldown(provider) {
    if (provider) this._lastIncidentAt.delete(provider);
    else this._lastIncidentAt.clear();
  }

  // Open a Gitea issue. ponytail: minimal payload, ignore failures.
  async open(provider, exhaustedSince, now = Date.now()) {
    if (!this.shouldReport(provider, exhaustedSince, now)) return { reported: false };
    const url = `${this._baseUrl}/api/v1/repos/${this._repo}/issues`;
    const body = {
      title: `prod-incident: pool ${provider} exhausted since ${new Date(exhaustedSince).toISOString()}`,
      body: [
        'Auto-generated by `dsh-key-rotation`.',
        '',
        `- provider: \`${provider}\``,
        `- exhaustedSince: \`${new Date(exhaustedSince).toISOString()}\``,
        '',
        'All keys in the pool are in cooldown or missing. Check OpenCode provider status and rotate keys.',
      ].join('\n'),
      labels: ['prod-incident'],
    };
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), INCIDENT_TIMEOUT_MS);
    try {
      const res = await this._fetch(url, {
        method: 'POST',
        headers: { authorization: `token ${this._token}`, 'content-type': 'application/json' },
        body: JSON.stringify(body),
        signal: ctrl.signal,
      });
      if (!res.ok) return { reported: false, status: res.status };
      const data = await res.json();
      this.markReported(provider, now);
      return { reported: true, number: data.number, url: data.html_url };
    } catch (_) {
      return { reported: false };
    } finally {
      clearTimeout(timer);
    }
  }
}
